executable = new.sh
arguments = $(file)
should_transfer_files = YES
when_to_transfer_output = ON_EXIT
log = new.log
output = new.out
error = new.err
request_cpus = 3
request_memory = 20GB
request_disk = 5GB
Requirements = $(requirements:True) && (OpSysMajorVer == 7) && (TARGET.has_avx)
+SingularityImage = "/home/sstray/test/condor/singu/machine.sif"
SINGULARITY_BIND_EXPR = "/data/user/sstray"
queue
#queue file from files_hdf5.txt


