executable = job.sh
arguments = $(file) $(ItemIndex)
should_transfer_files = YES
log = job.log
output = job.out
error = job.err
request_cpus = 1
request_memory = 10GB
request_disk = 10GB
#Requirements = $(requirements:True) && (OpSysMajorVer == 7) && (TARGET.has_avx)
#+SingularityImage = "/home/jvmead/dom_eff/RIDE_tcn/singu/hfpy.sif"
#SINGULARITY_BIND_EXPR = "/data/sim/IceCube/2012/filtered/level2"
queue file from files_corsika.txt
